openapi: 3.0.0
info:
  title: Login API
  description: API for user authentication including login and signup functionalities.
  version: "1.0"
servers:
  - url: 'http://localhost:13662'
paths:
  /api/login:
    post:
      summary: User login
      description: Verifies user credentials and returns a success message upon successful login.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
        '404':
          description: User not found
        '500':
          description: Server error

  /api/signup:
    post:
      summary: User signup
      description: Registers a new user with the provided email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '201':
          description: User created successfully
        '409':
          description: Email already in use
        '500':
          description: Server error during signup

  /api/getAllUserSubjects:
    post:
      summary: Retrieve all subjects for a user
      description: Returns a list of subjects associated with the provided user email.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Successfully retrieved subjects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '404':
          description: No subjects found for the user
        '500':
          description: Server error while fetching subjects
